# Data Preparation

In [1]:
import logging
import os
import pandas as pd

from bs4 import BeautifulSoup

In [2]:
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler("data_preparation.log"), logging.StreamHandler()],
)

In [ ]:
PATH_TO_HTML_REVIEWS = "./html"
GLASSDOOR_REVIEWS_CSV_PATH = "./validation_glassdoor_reviews.csv"
DATA_FRAME_COLUMNS = [
    "review_id",
    "company",
    "employee_role",
    "employee_detail",
    "review_text",
    "review_date",
    "star_rating",
    "sentiment",
]

In [4]:
def get_review_text(rating_div):
    rating_p = rating_div.find_all(
        "p", {"class": "review-details__review-details-module__isCollapsed"}
    )
    if len(rating_p) == 0:
        rating_p = rating_div.find_all(
            "p", {"class": "review-details__review-details-module__isExpanded"}
        )

    if len(rating_p) > 0:
        return rating_p[0].get_text()

    logging.warning("Texto da avaliação não encontrado!")
    return ""

In [5]:
def get_reviews_data(company, reviews):
    reviews_data = []
    for review in reviews:
        # Id
        review_id_li = review["id"]
        if review_id_li:
            review_id = review_id_li.split("_")[-1]
            logging.info(f"Avaliação {review_id} encontrada!")
        else:
            logging.warning("Id da avaliação não encontrado!")

        # Date
        review_date_span = review.find(
            "span", class_="timestamp__timestamp-module__reviewDate"
        )
        if review_date_span:
            review_date = review_date_span.get_text()
        else:
            logging.warning("Data da avaliação não encontrada!")

        # Employee role
        employee_role_span = review.find(
            "span", class_="review-details__review-details-module__employee"
        )
        if employee_role_span:
            employee_role = employee_role_span.get_text()
        else:
            logging.warning("Cargo do avaliador não encontrado!")

        # Employee detail
        employee_detail_div = review.find(
            "div", {"class": "review-details__review-details-module__employeeDetails"}
        )
        if employee_detail_div:
            employee_detail = employee_detail_div.get_text()
        else:
            logging.warning("Detalhe do avaliador não encontrado!")

        # Star rating
        star_rating_spans = review.find_all(
            "span", {"class": "review-details__review-details-module__overallRating"}
        )
        if star_rating_spans:
            star_rating_span = star_rating_spans[0]
            if star_rating_span:
                star_rating = float(star_rating_span.get_text().replace(",", "."))
            else:
                logging.warning("Nota de avaliação não foi encontrada!")
        else:
            logging.warning("Nenhuma nota de avaliação foi encontrada!")

        # Pro text
        pro_rating_divs = review.find_all(
            "div", {"class": "review-details__review-details-module__pro"}
        )
        if pro_rating_divs:
            pro_rating_div = pro_rating_divs[0]
            if pro_rating_div:
                logging.info("Buscando texto positivo da avaliação...")
                pro_review_text = get_review_text(pro_rating_div)
            else:
                logging.warning("Div da avaliação positiva não encontrada!")
        else:
            logging.warning("Nenhuma div de avaliação positiva foi encontrado!")

        # Con text
        con_rating_divs = review.find_all(
            "div", {"class": "review-details__review-details-module__con"}
        )
        if con_rating_divs:
            con_rating_div = con_rating_divs[0]
            if con_rating_div:
                logging.info("Buscando texto negativo da avaliação...")
                con_review_text = get_review_text(con_rating_div)
            else:
                logging.warning("Div da avaliação negativa não encontrada!")
        else:
            logging.warning("Nenhuma div de avaliação negativa foi encontrado!")

        # Append review data
        reviews_data.append(
            [
                review_id,
                company,
                employee_role,
                employee_detail,
                pro_review_text,
                review_date,
                star_rating,
                1,  # positive
            ]
        )
        reviews_data.append(
            [
                review_id,
                company,
                employee_role,
                employee_detail,
                con_review_text,
                review_date,
                star_rating,
                -1,  # negative
            ]
        )

    return reviews_data

In [6]:
if os.path.exists(GLASSDOOR_REVIEWS_CSV_PATH):
    reviews_df = pd.read_csv(GLASSDOOR_REVIEWS_CSV_PATH)
else:
    reviews_df = pd.DataFrame(columns=DATA_FRAME_COLUMNS)

In [7]:
reviews_df.head(2)

Empty DataFrame
Columns: [review_id, company, employee_role, employee_detail, review_text, review_date, star_rating, sentiment]
Index: []

In [8]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        0 non-null      object
 1   company          0 non-null      object
 2   employee_role    0 non-null      object
 3   employee_detail  0 non-null      object
 4   review_text      0 non-null      object
 5   review_date      0 non-null      object
 6   star_rating      0 non-null      object
 7   sentiment        0 non-null      object
dtypes: object(8)
memory usage: 132.0+ bytes

In [14]:
for filename in os.listdir(PATH_TO_HTML_REVIEWS):
    if filename.endswith(".html"):
        file_path = os.path.join(PATH_TO_HTML_REVIEWS, filename)

        logging.info(f"Abrindo o arquivo: {file_path}")
        with open(file_path, "r", encoding="utf-8") as f:
            html_page = "".join(f.readlines())
            soup = BeautifulSoup(html_page, "html.parser")

            if soup.title:
                if soup.title.get_text() != "Security | Glassdoor":
                    company_p = soup.find_all("p", {"class": "employerName"})[0]
                    company = company_p.get_text()

                    logging.info(f"Buscando Avaliações da Empresa: {company}")

                    reviews = soup.find_all(
                        "li", id=lambda x: x and x.startswith("empReview_")
                    )

                    reviews_data = get_reviews_data(company, reviews)

                    df = pd.DataFrame(reviews_data, columns=DATA_FRAME_COLUMNS)

                    for index, row in df.iterrows():
                        new_review_id = int(row["review_id"])
                        if new_review_id not in reviews_df["review_id"].values:
                            reviews_df = pd.concat(
                                [reviews_df, df],
                                ignore_index=True,
                            )

                            # Since we have two comments with same id for each review,
                            # we must concat the new review df only once
                            break

2025-03-23 13:11:00,718 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_1.html

2025-03-23 13:11:00,870 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:00,870 [INFO] Avaliação 84941541 encontrada!
2025-03-23 13:11:00,870 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,880 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,881 [INFO] Avaliação 85370906 encontrada!
2025-03-23 13:11:00,887 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,887 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,893 [INFO] Avaliação 85366318 encontrada!
2025-03-23 13:11:00,896 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,901 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,903 [INFO] Avaliação 85381802 encontrada!
2025-03-23 13:11:00,906 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,909 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,912 [INFO] Avaliação 84437364 encontrada!
2025-03-23 13:11:00,917 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,920 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,922 [INFO] Avaliação 84780075 encontrada!
2025-03-23 13:11:00,926 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,928 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,931 [INFO] Avaliação 84684860 encontrada!
2025-03-23 13:11:00,935 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,937 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,937 [INFO] Avaliação 84672201 encontrada!
2025-03-23 13:11:00,937 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,937 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,948 [INFO] Avaliação 84375405 encontrada!
2025-03-23 13:11:00,953 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,956 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:00,957 [INFO] Avaliação 84510975 encontrada!
2025-03-23 13:11:00,959 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:00,959 [INFO] Buscando texto negativo da avaliação...
C:\Users\stevi\AppData\Local\Temp\ipykernel_15820\3269081307.py:28: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  reviews_df = pd.concat(
2025-03-23 13:11:00,977 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_2.html
2025-03-23 13:11:01,135 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:01,142 [INFO] Avaliação 84510975 encontrada!
2025-03-23 13:11:01,145 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,147 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,149 [INFO] Avaliação 84223951 encontrada!
2025-03-23 13:11:01,152 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,155 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,157 [INFO] Avaliação 84489041 encontrada!
2025-03-23 13:11:01,160 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,162 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,164 [INFO] Avaliação 84185646 encontrada!
2025-03-23 13:11:01,168 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,170 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,173 [INFO] Avaliação 84141668 encontrada!
2025-03-23 13:11:01,176 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,176 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,176 [INFO] Avaliação 83619207 encontrada!
2025-03-23 13:11:01,186 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,189 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,192 [INFO] Avaliação 84415829 encontrada!
2025-03-23 13:11:01,197 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,202 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,204 [INFO] Avaliação 84167038 encontrada!
2025-03-23 13:11:01,208 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,210 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,212 [INFO] Avaliação 84225265 encontrada!
2025-03-23 13:11:01,216 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,219 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,222 [INFO] Avaliação 82206428 encontrada!
2025-03-23 13:11:01,227 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,233 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,241 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_3.html
2025-03-23 13:11:01,405 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:01,415 [INFO] Avaliação 83731427 encontrada!
2025-03-23 13:11:01,420 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,420 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,420 [INFO] Avaliação 83827298 encontrada!
2025-03-23 13:11:01,430 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,430 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,435 [INFO] Avaliação 84209582 encontrada!
2025-03-23 13:11:01,439 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,439 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,444 [INFO] Avaliação 81062176 encontrada!
2025-03-23 13:11:01,447 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,450 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,453 [INFO] Avaliação 83410655 encontrada!
2025-03-23 13:11:01,457 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,459 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,459 [INFO] Avaliação 78987841 encontrada!
2025-03-23 13:11:01,459 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,468 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,471 [INFO] Avaliação 84001889 encontrada!
2025-03-23 13:11:01,475 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,480 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,481 [INFO] Avaliação 82502454 encontrada!
2025-03-23 13:11:01,486 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,488 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,488 [INFO] Avaliação 80113724 encontrada!
2025-03-23 13:11:01,488 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,501 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,503 [INFO] Avaliação 82902870 encontrada!
2025-03-23 13:11:01,509 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,509 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,520 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_4.html
2025-03-23 13:11:01,670 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:01,672 [INFO] Avaliação 83228478 encontrada!
2025-03-23 13:11:01,672 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,672 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,686 [INFO] Avaliação 83203375 encontrada!
2025-03-23 13:11:01,689 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,690 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,693 [INFO] Avaliação 83039620 encontrada!
2025-03-23 13:11:01,696 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,700 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,703 [INFO] Avaliação 83230157 encontrada!
2025-03-23 13:11:01,708 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,708 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,708 [INFO] Avaliação 83056827 encontrada!
2025-03-23 13:11:01,708 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,723 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,725 [INFO] Avaliação 83238341 encontrada!
2025-03-23 13:11:01,729 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,733 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,735 [INFO] Avaliação 82372096 encontrada!
2025-03-23 13:11:01,740 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,745 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,745 [INFO] Avaliação 82843799 encontrada!
2025-03-23 13:11:01,752 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,756 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,758 [INFO] Avaliação 82334798 encontrada!
2025-03-23 13:11:01,760 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,763 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,765 [INFO] Avaliação 82723602 encontrada!
2025-03-23 13:11:01,769 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,772 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,779 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_5.html
2025-03-23 13:11:01,965 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:01,965 [INFO] Avaliação 82723602 encontrada!
2025-03-23 13:11:01,983 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,985 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,988 [INFO] Avaliação 82778935 encontrada!
2025-03-23 13:11:01,990 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:01,990 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:01,997 [INFO] Avaliação 82728259 encontrada!
2025-03-23 13:11:02,001 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,003 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,007 [INFO] Avaliação 81896164 encontrada!
2025-03-23 13:11:02,009 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,010 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,010 [INFO] Avaliação 82053970 encontrada!
2025-03-23 13:11:02,019 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,022 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,023 [INFO] Avaliação 82677884 encontrada!
2025-03-23 13:11:02,023 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,023 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,033 [INFO] Avaliação 82691730 encontrada!
2025-03-23 13:11:02,037 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,041 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,043 [INFO] Avaliação 81153234 encontrada!
2025-03-23 13:11:02,046 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,048 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,051 [INFO] Avaliação 82346605 encontrada!
2025-03-23 13:11:02,055 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,058 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,060 [INFO] Avaliação 80791471 encontrada!
2025-03-23 13:11:02,064 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,067 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,072 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_6.html
2025-03-23 13:11:02,205 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:02,205 [INFO] Avaliação 82237819 encontrada!
2025-03-23 13:11:02,205 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,205 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,221 [INFO] Avaliação 82364584 encontrada!
2025-03-23 13:11:02,224 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,226 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,228 [INFO] Avaliação 82306432 encontrada!
2025-03-23 13:11:02,231 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,235 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,238 [INFO] Avaliação 81382236 encontrada!
2025-03-23 13:11:02,242 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,245 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,247 [INFO] Avaliação 82089270 encontrada!
2025-03-23 13:11:02,251 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,254 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,256 [INFO] Avaliação 80983984 encontrada!
2025-03-23 13:11:02,260 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,260 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,260 [INFO] Avaliação 81880315 encontrada!
2025-03-23 13:11:02,268 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,272 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,273 [INFO] Avaliação 82052641 encontrada!
2025-03-23 13:11:02,273 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,273 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,273 [INFO] Avaliação 81277887 encontrada!
2025-03-23 13:11:02,285 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,288 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,291 [INFO] Avaliação 81577445 encontrada!
2025-03-23 13:11:02,295 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,297 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,304 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_7.html
2025-03-23 13:11:02,445 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:02,452 [INFO] Avaliação 81396468 encontrada!
2025-03-23 13:11:02,452 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,461 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,467 [INFO] Avaliação 80985682 encontrada!
2025-03-23 13:11:02,471 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,475 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,477 [INFO] Avaliação 81416995 encontrada!
2025-03-23 13:11:02,480 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,484 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,487 [INFO] Avaliação 81055470 encontrada!
2025-03-23 13:11:02,490 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,494 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,495 [INFO] Avaliação 80323734 encontrada!
2025-03-23 13:11:02,502 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,505 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,508 [INFO] Avaliação 81288938 encontrada!
2025-03-23 13:11:02,512 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,512 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,520 [INFO] Avaliação 80848344 encontrada!
2025-03-23 13:11:02,522 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,525 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,528 [INFO] Avaliação 78497185 encontrada!
2025-03-23 13:11:02,532 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,535 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,538 [INFO] Avaliação 80473649 encontrada!
2025-03-23 13:11:02,544 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,544 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,551 [INFO] Avaliação 80985820 encontrada!
2025-03-23 13:11:02,556 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,562 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,570 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_8.html
2025-03-23 13:11:02,773 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:02,773 [INFO] Avaliação 80801481 encontrada!
2025-03-23 13:11:02,789 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,789 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,789 [INFO] Avaliação 80784274 encontrada!
2025-03-23 13:11:02,789 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,804 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,807 [INFO] Avaliação 80214449 encontrada!
2025-03-23 13:11:02,810 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,810 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,817 [INFO] Avaliação 79785974 encontrada!
2025-03-23 13:11:02,822 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,825 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,825 [INFO] Avaliação 80734764 encontrada!
2025-03-23 13:11:02,834 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,840 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,843 [INFO] Avaliação 79410924 encontrada!
2025-03-23 13:11:02,843 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,851 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,856 [INFO] Avaliação 78520689 encontrada!
2025-03-23 13:11:02,860 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,863 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,868 [INFO] Avaliação 80216210 encontrada!
2025-03-23 13:11:02,873 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,873 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,873 [INFO] Avaliação 80059329 encontrada!
2025-03-23 13:11:02,885 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,890 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,893 [INFO] Avaliação 79817459 encontrada!
2025-03-23 13:11:02,896 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:02,898 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:02,904 [INFO] Abrindo o arquivo: ./html\Sankhya Gestão de Negócios_page_9.html
2025-03-23 13:11:03,098 [INFO] Buscando Avaliações da Empresa: Sankhya Gestão de Negócios
2025-03-23 13:11:03,101 [INFO] Avaliação 79817459 encontrada!
2025-03-23 13:11:03,101 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,112 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,115 [INFO] Avaliação 79176474 encontrada!
2025-03-23 13:11:03,119 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,125 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,128 [INFO] Avaliação 79204087 encontrada!
2025-03-23 13:11:03,130 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,134 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,137 [INFO] Avaliação 79213661 encontrada!
2025-03-23 13:11:03,139 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,139 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,146 [INFO] Avaliação 79611368 encontrada!
2025-03-23 13:11:03,153 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,155 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,155 [INFO] Avaliação 79601670 encontrada!
2025-03-23 13:11:03,169 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,173 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,174 [INFO] Avaliação 79886919 encontrada!
2025-03-23 13:11:03,174 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,174 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,185 [INFO] Avaliação 79544904 encontrada!
2025-03-23 13:11:03,188 [INFO] Buscando texto positivo da avaliação...
2025-03-23 13:11:03,191 [INFO] Buscando texto negativo da avaliação...
2025-03-23 13:11:03,194 [INFO] Avaliação 79758062 encontrada!

In [15]:
reviews_df.head(2)

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment
0,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano","Salário compatível, oportunidade de desenvolvi...",2 de mar. de 2024,5.0,1
1,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano",Não tenho o que reclamar da empresa,2 de mar. de 2024,5.0,-1

In [16]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8212 entries, 0 to 8211
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   review_id        8212 non-null   object
 1   company          8212 non-null   object
 2   employee_role    8212 non-null   object
 3   employee_detail  8212 non-null   object
 4   review_text      8212 non-null   object
 5   review_date      8212 non-null   object
 6   star_rating      8212 non-null   float64
 7   sentiment        8212 non-null   object
dtypes: float64(1), object(7)
memory usage: 513.4+ KB

In [ ]:
reviews_df.to_csv("./validation_glassdoor_reviews.csv", index=False)