In [1]:
import pandas as pd

In [2]:
reviews_df = pd.read_csv("../data_preparation/glassdoor_reviews_annotated.csv")

In [3]:
reviews_df.head()

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment,annotated
0,82630669,Tecnomapas,Recepcionista,"Ex-funcionário(a), mais de um ano","Companheirismo entre os colegas, oportunidade ...",2023-12-15,5.0,1,0
1,82630669,Tecnomapas,Recepcionista,"Ex-funcionário(a), mais de um ano",Não tive nenhum ponto negativo,2023-12-15,5.0,0,1
2,74420027,Tecnomapas,Analista Desenvolvedor,Ex-freelancer,Equipe bem prestativa e ótima de se trabalhar.,2023-03-11,4.0,1,0
3,74420027,Tecnomapas,Analista Desenvolvedor,Ex-freelancer,Modo home office ainda tem que ser melhorado.,2023-03-11,4.0,-1,0
4,60212043,Tecnomapas,Funcionário confidencial,"Ex-funcionário(a), menos de um ano",Única vantagem era o trabalho ser home office,2022-02-24,1.0,0,1

In [4]:
reviews_df["annotated"] = 0

In [5]:
reviews_df["sentiment"].value_counts()

sentiment
 1    1269
-1    1021
 0     242
Name: count, dtype: int64

In [6]:
reviews_df["sentiment"] = reviews_df["sentiment"].apply(
    lambda x: 2 if x == -1 else x
)

In [7]:
reviews_df["sentiment"].value_counts()

sentiment
1    1269
2    1021
0     242
Name: count, dtype: int64

In [8]:
num_samples = int(20*240/100)
num_samples

48

In [9]:
random_positive_reviews_df = reviews_df[reviews_df["sentiment"] == 1].sample(
    n=num_samples
)

In [10]:
random_positive_reviews_df["sentiment"].value_counts()

sentiment
1    48
Name: count, dtype: int64

In [11]:
random_negative_reviews_df = reviews_df[reviews_df["sentiment"] == 2].sample(
    n=num_samples
)

In [12]:
random_negative_reviews_df["sentiment"].value_counts()

sentiment
2    48
Name: count, dtype: int64

In [13]:
random_neutral_reviews_df = reviews_df[reviews_df["sentiment"] == 0].sample(
    n=num_samples
)

In [14]:
random_neutral_reviews_df["sentiment"].value_counts()

sentiment
0    48
Name: count, dtype: int64

In [15]:
golden_df = pd.concat(
    [
        random_positive_reviews_df,
        random_negative_reviews_df,
        random_neutral_reviews_df,
    ]
)

In [16]:
golden_df["sentiment"].value_counts()

sentiment
1    48
2    48
0    48
Name: count, dtype: int64

In [17]:
golden_df.head(5)

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment,annotated
1944,50539336,Grupo Bom Futuro,Motorista D,Funcionário(a) atual,"Empresa boa, porém falta algumas melhores para...",2021-08-01,3.0,1,0
616,52165795,Amaggi,Funcionário confidencial,"Ex-funcionário(a), mais de 3 anos","Empresa muito boa, tem bons procedimentos inte...",2021-09-06,5.0,1,0
1528,74973659,DSS Tecnologia,Digitador,Funcionário(a) atual,folga dia sim e dia não.,2023-03-28,4.0,1,0
2170,44377014,"Log, Lab. Inteligência Digital",Analista De Sistemas,Funcionário(a) atual,Ambiente agradável\r\n\r\nPessoas dedicadas e ...,2021-03-22,4.0,1,0
1362,26770042,Cigam Software Corporativo,Implementador,Funcionário(a) atual,"Valorizaçao do funcionário, preocupação com o ...",2016-06-28,4.0,1,0

In [18]:
golden_df.to_csv("golden_reviews_df.csv", index=False)